### 관리자 권한으로 문제집 추가하기
POST /api/admin/workbooks HTTP/1.1
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer botobo.access.token
Host: localhost:8080

{
  "name" : "JAVA",
  "opened" : true
}

### 관리자 권한으로 카드 추가하기
POST /api/admin/cards HTTP/1.1
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer botobo.access.token
Host: localhost:8080

{
  "question" : "질문1",
  "answer" : "답변1",
  "workbookId" : 1
}