### 카드 생성
POST /api/cards HTTP/1.1
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer botobo.access.token
Host: localhost:8080

{
  "question": "이것은 질문입니다!",
  "answer": "그리고 답변입니다~",
  "workbookId": 1
}

### 카드 수정
PUT /api/cards/1 HTTP/1.1
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer botobo.access.token
Host: localhost:8080

{
  "question": "수정된 질문입니다!",
  "answer": "그리고 수정된 답변입니다~",
  "workbookId": 1,
  "encounterCount": 5,
  "bookmark": true,
  "nextQuiz": true
}

### 카드 삭제
DELETE /api/cards/1 HTTP/1.1
Authorization: Bearer botobo.access.token
Host: localhost:8080