### 퀴즈 생성하기
POST /api/quizzes HTTP/1.1
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer botobo.access.token
Host: localhost:8080

{
  "workbookIds": [
    1,
    2,
    3
  ]
}

### 비회원용 퀴즈 생성하기
GET /api/quizzes/guest HTTP/1.1
Host: localhost:8080