# https://github.com/login/oauth/authorize?client_id={client_id

### 문제집 추가

POST /api/workbooks HTTP/1.1
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer botobo.access.token
Host: localhost:8080

{
  "name" : "Java 문제집",
  "opened" : true
}

### 로그인 유저 문제집 보기

GET /api/workbooks HTTP/1.1
Authorization: Bearer botobo.access.token
Host: localhost:8080

### 비회원 문제집 보기

GET /api/workbooks HTTP/1.1
Host: localhost:8080

### 문제집별 카드 모아보기

GET /api/workbooks/1/cards HTTP/1.1
Authorization: Bearer botobo.access.token
Host: localhost:8080

### 문제집 수정하기

PUT /api/workbooks/1 HTTP/1.1
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer botobo.access.token
Host: localhost:8080

{
  "name" : "Java 문제집",
  "opened" : true,
  "cardCount" : 0
}

### 문제집 삭제하기

DELETE /api/workbooks/1 HTTP/1.1
Authorization: Bearer botobo.access.token
Host: localhost:8080