pipeline {
     agent any
     tools {
        nodejs "nodejs"
        git "git"
    }
     stages {
        stage("Build") {
            steps {
              dir('frontend'){
                sh "yarn"
                sh "yarn build:dev"
               }
            }
        }
    }
}
