pipeline {
     agent any
     tools {
        nodejs "nodejs"
        git "git"
    }
     stages {
        stage("Build") {
            steps {
              dir('frontend'){
                sh "yarn"
                sh "yarn build:dev"
               }
            }
        }
        stage('SSH transfer') {
            steps([$class: 'BapSshPromotionPublisherPlugin']) {
                sshPublisher(
                    continueOnError: false, failOnError: true,
                    publishers: [
                        sshPublisherDesc(
                            configName: "botobo-frontend-develop",
                            verbose: true,
                            transfers: [
                                sshTransfer(
                                     sourceFiles: "/frontend/dist/index.html", 
                                     removePrefix: "/frontend",
                                    remoteDirectory: ""
  )
                            ]
                        )
                    ]
                )
            }
        }
      }
}
