pipeline {
     agent any
     tools {
        nodejs "nodejs"
        git "git"
    }
     stages {
        stage("Build") {
            steps {
              dir('frontend'){
                sh "yarn"
                sh "yarn build:dev"
               }
            }
        }
      }
     stage('SSH transfer') {
            steps([$class: 'BapSshPromotionPublisherPlugin']) {
                sshPublisher(
                    continueOnError: false, failOnError: true,
                    publishers: [
                        sshPublisherDesc(
                            configName: "botobo-frontend-develop",
                            verbose: true,
                            transfers: [
                                sshTransfer(
                                     sourceFiles: "${workspace}/frontend/dist/**", 
                                     removePrefix: "${workspace}/frontend",
                                    remoteDirectory: "/2021-botobo/frontend",
                                    execCommand: "hi~~" //원격지에서 실행할 커맨드
  )
                            ]
                        )
                    ]
                )
            }
        }
}
