# test

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: create
  config:
    activate:
      on-profile: test
  flyway:
    enabled: false

github:
  client:
    id: githubId
    secret: githubSecret
  url:
    access-token: https://github.com/login/oauth/access_token
    profile: https://api.github.com/user

google:
  client:
    id: googleId
    secret: googleSecret
    redirect-uri: googleRedirectUri
    grant-type: authorization_code
  url:
    access-token: https://oauth2.googleapis.com/token
    profile: https://openidconnect.googleapis.com/v1/userinfo

security:
  jwt:
    token:
      secret-key: testsecretkey
      expire-length: 3600000

aws:
  cloudfront:
    url-format: https://d1mlkr1uzdb8as.cloudfront.net/%s
  s3:
    bucket: s3-botobo-storage
  user-default-image: botobo-default-profile.png

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
