logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

# region.stack -> 로컬에서는 가상의 region이 필요하므로 명시
# stack.auto -> 프로젝트 배포시 기본으로 CloudFormation 구성을 시작하기 때문에 설정한 CloudFormation이 없으면 프로젝트 실행이 되지 않음.
# 해당 기능을 사용하지 않도록 false로 설정.
cloud:
 aws:
   region:
    static: ap-northeast-2
   stack:
    auto: false
