# test

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  config:
    activate:
      on-profile: test

github:
  client:
    id: a
    secret: a
  url:
    access-token: https://github.com/login/oauth/access_token
    profile: https://api.github.com/user

security:
  jwt:
    token:
      secret-key: testsecretkey
      expire-length: 3600000

aws:
  cloudfront:
    url-format: https://d1mlkr1uzdb8as.cloudfront.net/%s
  s3:
    bucket: s3-botobo-storage
  user-default-image: botobo-default-profile.png

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false