# test

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  config:
    activate:
      on-profile: test

github:
  client:
    id: githubId
    secret: githubSecret
  url:
    access-token: https://github.com/login/oauth/access_token
    profile: https://api.github.com/user

google:
  client:
    id: googleId
    secret: googleSecret
    redirect-uri: googleRedirectUri
    grant-type: authorization_code
  url:
    access-token: https://oauth2.googleapis.com/token
    profile: https://openidconnect.googleapis.com/v1/userinfo

security:
  jwt:
    token:
      secret-key: testsecretkey
      expire-length: 3600000