ALTER TABLE `USER` AUTO_INCREMENT=1;
ALTER TABLE CARD AUTO_INCREMENT=1;
ALTER TABLE HEART AUTO_INCREMENT=1;
ALTER TABLE TAG AUTO_INCREMENT=1;
ALTER TABLE WORKBOOK AUTO_INCREMENT=1;
ALTER TABLE WORKBOOK_TAG AUTO_INCREMENT=1;
