name: frontend-dev

on:
  push:
    branches: [dev/*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.SUBMODULE_KEY }}
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: yarn install and build
        run: |
          cd frontend
          yarn
          yarn build:dev

      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_DEV_KEY_FRONT }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_ACCESS_DEV_SECRET_KEY_FRONT }}'
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            frontend/dist s3://botobo
