name: frontend-dev

on:
  push:
    branches: [dev/*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.SUBMODULE_KEY }}
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: yarn install and build
        run: |
          cd frontend
          yarn
          yarn build:dev

      - name: deploy
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: 'botobo'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_DEV_KEY_FRONT }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_DEV_SECRET_KEY_FRONT }}
          AWS_REGION: 'ap-northeast-2'
